# ============================================================================
# Gmail Collector Configuration - DETAILED GUIDANCE
# ============================================================================

token_file: "data/gmail_token.json"
credentials_file: "data/gmail_credentials.json"

output_dir: "output/gmail"
# Note: State is managed automatically by the collector in output/gmail/.gmail_state.json
# This location allows the state file to be tracked in git for GitHub Actions workflow
rate_limit_seconds: 1.0
batch_size: 50  # Recommended: 50 (values >100 may cause Gmail API rate limiting)

scopes:
  - "https://www.googleapis.com/auth/gmail.readonly"
  - "https://www.googleapis.com/auth/gmail.modify"
  - "https://www.googleapis.com/auth/gmail.labels"
  - "https://www.googleapis.com/auth/gmail.send"
default_filters:
  max_age_days: 30
  include_keywords: []
  exclude_keywords: []

# ============================================================================
# COMPREHENSIVE RULE EXAMPLES
# ============================================================================
#
# Rule Action Types:
# ------------------
# Simple Actions:
#   - save              : Save message to markdown file
#   - archive           : Remove INBOX label (archive message)
#   - mark_read         : Remove UNREAD label
#   - delete            : Move to trash (recoverable for 30 days)
#   - delete_permanent  : Permanently delete (cannot be recovered)
#
# Parametrized Actions:
#   - label:<name>        : Add label (use / for nesting, e.g. label:parent/child)
#   - remove_label:<name> : Remove label
#   - forward:<email>     : Forward message to email address
#
# Gmail Query Syntax:
# -------------------
# Operators: from:, to:, subject:, label:, has:, is:, in:
#           after:, before:, newer:, older:, category:
#           size:, larger:, smaller:, filename:, cc:, bcc:
#
# Examples:
#   from:user@example.com
#   subject:"important update"
#   label:unread has:attachment
#   after:2025/01/01 before:2025/12/31
#   is:unread -is:starred
#
# Filter Criteria:
# ----------------
#   max_age_days      : Only process messages from last N days
#   include_keywords  : Message must contain at least one keyword (case-insensitive)
#   exclude_keywords  : Skip message if it contains any keyword
#
# Keywords support wildcards:
#   "AI*"     : Matches "AI", "AIops", "AI-powered"
#   "*machine learning*" : Matches anywhere in text
#
# ============================================================================

rules:
  - name: "readwise"
    query: >
      from:alexmcfarland@substack.com OR
      from:mlearning@substack.com
    actions:
      - "forward:wtread@library.readwise.io"
      - "save"
      - "archive"
      - "label:ai-notebook"
    max_messages: 20
    save_attachments: false
    filters:
      max_age_days: 20
      include_keywords: []
      exclude_keywords: []

  - name: "notebooklm"
    query: >
      from:aiadopters@substack.com OR
      from:team@newsletter.learnprompting.org OR
      from:refactoring+essays@substack.com OR
      from:aisupremacy+guides@substack.com
    actions:
      - "save"
      - "archive"
      - "label:ai-notebook"
    max_messages: 20
    save_attachments: false
    filters:
      max_age_days: 20
      include_keywords: []
      exclude_keywords: []

  - name: "snippets"
    query: >
      from:creatorsai@substack.com OR
      from:bensbites@substack.com OR
      from:whytryai+10x-ai@substack.com OR
      from:whytryai@substack.com
    actions:
      - "save"
      - "archive"
      - "label:snippets"
    max_messages: 20
    save_attachments: false
    filters:
      max_age_days: 20
      include_keywords: []
      exclude_keywords: []

  - name: "on-design"
    query: >
      from:noreply@medium.com OR
      from:designwithai@substack.com OR
      from:uxco@substack.com OR
      from:jakobnielsenphd@substack.com OR
      from:alertbox@nngroup.com
    actions:
      - "save"
      - "archive"
      - "label:de-notebook"
    max_messages: 20
    save_attachments: false
    filters:
      max_age_days: 20
      include_keywords: []
      exclude_keywords: []

  - name: "delete"
    query: "from:team_at_mail_perplexity_ai_hvg2c2jtvk_702c6023@privaterelay.appleid.com AND subject:Your report is ready"
    actions:
      - "delete"
    max_messages: 20
    save_attachments: false
    filters:
      max_age_days: 20
      include_keywords: []
      exclude_keywords: []

label_rules:
  - name: "intake"
    trigger_label: "intake"
    actions:
      - "save"              # Save before archiving
      - "archive"           # Remove from inbox
    remove_trigger: true    # Remove "intake" label after processing
    max_messages: 50
    save_attachments: true
    filters:
      exclude_keywords:
        - ""
