# Gmail Collector Configuration Example
# This file demonstrates both query-based rules and label-based trigger rules

# Output directory for saved emails
output_dir: "./output/gmail"

# OAuth token and credentials paths
token_file: "./data/gmail_token.json"
credentials_file: "./data/gmail_credentials.json"

# API rate limiting (seconds between requests)
rate_limit_seconds: 1.0

# Gmail API batch size (recommended: 50 to avoid rate limiting)
batch_size: 50

# OAuth scopes (permissions required)
scopes:
  - "https://www.googleapis.com/auth/gmail.readonly"    # Read emails
  - "https://www.googleapis.com/auth/gmail.modify"      # Archive/mark read
  - "https://www.googleapis.com/auth/gmail.labels"      # Add/remove labels
  - "https://www.googleapis.com/auth/gmail.send"        # Send/forward emails

# Global filters applied to ALL rules
default_filters:
  max_age_days: 30
  exclude_keywords:
    - "promotional"
    - "spam"
    - "unsubscribe"

# =============================================================================
# QUERY-BASED RULES (Traditional email collection)
# =============================================================================
# These rules search for emails using Gmail query syntax
rules:
  - name: "design-information"
    query: "from:noreply@medium.com OR from:designwithai@substack.com"
    actions:
      - "save"              # Save as markdown
      - "archive"           # Remove from inbox
      - "label:processed"   # Add "processed" label
    max_messages: 20
    save_attachments: false
    filters:
      max_age_days: 20
      include_keywords:
        - "design"
        - "AI"
        - "UX"

  - name: "github-notifications"
    query: "from:notifications@github.com is:unread"
    actions:
      - "save"
      - "mark_read"
      - "label:github"
    max_messages: 50
    save_attachments: true
    filters:
      include_keywords:
        - "pull request"
        - "issue"
        - "review"

# =============================================================================
# LABEL-BASED TRIGGER RULES (NEW FEATURE)
# =============================================================================
# These rules watch for manually applied labels and trigger actions
# Workflow: You manually apply a label → Collector detects it → Actions execute
label_rules:
  # Example 1: Manual Archive Queue
  # Usage: Apply "to-archive" label to any email you want to archive
  - name: "Manual Archive Queue"
    trigger_label: "to-archive"
    actions:
      - "save"              # Save before archiving
      - "archive"           # Remove from inbox
    remove_trigger: true    # Remove "to-archive" label after processing
    max_messages: 50
    save_attachments: true
    filters:
      # Optional: Filter archived content
      exclude_keywords:
        - "promotional"

  # Example 2: Forward to Assistant
  # Usage: Apply "forward-to-assistant" label to emails to forward
  - name: "Forward to Assistant"
    trigger_label: "forward-to-assistant"
    actions:
      - "forward:assistant@example.com"  # Forward email
      - "label:forwarded"                 # Track forwarded emails
    remove_trigger: true
    max_messages: 20
    save_attachments: false

  # Example 3: Important Document Archive
  # Usage: Apply "archive-important" to critical emails
  - name: "Important Archive"
    trigger_label: "archive-important"
    actions:
      - "save"
      - "label:archived"
      - "label:important-backup"
    remove_trigger: true
    max_messages: 30
    save_attachments: true
    filters:
      max_age_days: 90  # Only archive recent items

  # Example 4: Processing Queue (Keep Trigger)
  # Usage: Track emails in a queue without removing the label
  - name: "Processing Queue"
    trigger_label: "in-queue"
    actions:
      - "save"
      - "label:processed"
    remove_trigger: false   # Keep "in-queue" label for manual tracking
    max_messages: 100
    save_attachments: false

  # Example 5: Nested Label Example
  # Usage: Use Gmail's nested labels (folder-like structure)
  - name: "Action Required - Archive"
    trigger_label: "actions/archive"  # Nested label: "actions/archive"
    actions:
      - "save"
      - "archive"
      - "label:actions/completed"  # Nested label for completion
    remove_trigger: true
    max_messages: 25
    save_attachments: true

  # Example 6: Delete Queue
  # Usage: Mark emails for deletion before permanently removing
  - name: "Delete Queue"
    trigger_label: "to-delete"
    actions:
      - "save"              # Backup before deletion
      - "delete"            # Move to trash (30-day recovery)
    remove_trigger: true
    max_messages: 50
    save_attachments: false
    filters:
      # Safety: Don't delete emails with these keywords
      exclude_keywords:
        - "important"
        - "urgent"
        - "invoice"
        - "receipt"

# =============================================================================
# CONFIGURATION NOTES
# =============================================================================

# Label Rules vs Query Rules:
# - Query rules: Automatic based on search criteria
# - Label rules: Manual triggering by applying labels
# - Both can process the same email independently (separate state tracking)
# - State key format: query rules use "{message_id}", label rules use "label_rule:{rule_name}:{message_id}"

# Label Naming:
# - Alphanumeric, dash, underscore, slash only
# - Use "/" for nesting: "parent/child" creates "parent" folder with "child" label
# - Case-insensitive (normalized to lowercase)
# - Examples: "to-archive", "actions/forward", "process-later"

# Available Actions (same for both rule types):
# - save: Save email as markdown file
# - archive: Remove from inbox (move to All Mail)
# - mark_read: Mark as read
# - label:name: Add label (creates if doesn't exist)
# - remove_label:name: Remove label
# - forward:email@domain.com: Forward to recipient
# - delete: Move to trash (recoverable for 30 days)
# - delete_permanent: Permanently delete (irreversible)

# Filters:
# - max_age_days: Only process emails newer than N days
# - include_keywords: Must contain at least one (supports wildcards: *, ?)
# - exclude_keywords: Skip if contains any (supports wildcards)
# - Wildcards: "claude*" matches "claude", "claude-code", etc.

# remove_trigger Option:
# - true: Remove trigger label after processing (recommended for most cases)
# - false: Keep trigger label for manual tracking or multi-pass processing
# - State tracking prevents re-processing even if label remains

# Best Practices:
# 1. Start with remove_trigger: true to avoid clutter
# 2. Use descriptive label names: "to-archive" not "ta"
# 3. Test with max_messages: 5 before increasing
# 4. Use filters to prevent accidental processing
# 5. Always include "save" action before "delete" for backup
# 6. Create nested labels for organization: "actions/archive", "actions/forward"

# Example Workflow:
# 1. Configure label rules in this file
# 2. Run collector once to ensure no errors
# 3. Manually apply trigger labels to test emails in Gmail
# 4. Run collector again to process labeled emails
# 5. Check output directory for saved emails
# 6. Verify trigger labels removed (if configured)
# 7. Check state file to confirm processing tracked
